default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: devdb
  username: postgres
  password: Friendship@2480

test:
  <<: *default
  encoding: unicode
  database: testdb
  username: postgres
  password: Friendship@2480

production:
  <<: *default
